# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:6.0.17
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env
    container_name: "web_template_mongodb"

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    container_name: "web_template_redis"

volumes:
  redis:
    driver: local
  mongodb:
    driver: local
